/**
 * Black Box Scorer
 *
 * Treats the LLM as a black box. Confidence is measured by how
 * consistent multiple independently sampled candidate responses are
 * with each other — high pairwise similarity → low hallucination risk.
 * This is the SelfCheckGPT approach.
 *
 * Real path (when `secondSample` + `embedText` are supplied):
 *   1. `secondSample` is an independent higher-temperature resample of the
 *      same question, generated by the actual LLM (see server.js's parallel
 *      resample call)
 *   2. Embed both the original response and the resample with the real local
 *      sentence-embedding model already used for RAG retrieval
 *   3. Confidence = cosine similarity between the two embeddings — genuine
 *      semantic consistency, not lexical overlap
 *
 * Fallback path (no resample/embedder available): reconstructs deterministic
 * text mutations of the single response and compares them with TF-IDF cosine
 * similarity, same as before — keeps the scorer from crashing or returning a
 * constant when the real dependencies aren't wired up.
 */

'use strict';

// ── Tokenise + TF vector (fallback path only) ────────────────────────────────
function tokenise(text) {
  return text.toLowerCase().split(/\W+/).filter(w => w.length > 2);
}

function tfVector(tokens) {
  const vec = {};
  tokens.forEach(t => { vec[t] = (vec[t] || 0) + 1; });
  const total = tokens.length || 1;
  Object.keys(vec).forEach(k => { vec[k] /= total; });
  return vec;
}

function tfCosineSimilarity(a, b) {
  const keysA = Object.keys(a);
  let dot = 0, magA = 0, magB = 0;
  keysA.forEach(k => {
    dot  += (a[k] || 0) * (b[k] || 0);
    magA += a[k] ** 2;
  });
  Object.values(b).forEach(v => { magB += v ** 2; });
  return (magA > 0 && magB > 0) ? dot / (Math.sqrt(magA) * Math.sqrt(magB)) : 0;
}

function generateCandidates(response, context) {
  const base = response.trim();
  const sentences = base.split(/(?<=[.!?])\s+/).filter(Boolean);
  const shuffled  = [...sentences].sort(() => 0.5 - Math.random()).join(' ');
  const stripped  = base.replace(/\b(the|a|an|is|are|was|were|and|or|but|in|on|at|to|of)\b/gi, '').replace(/\s+/g,' ').trim();
  const contextAnchored = context
    ? (context.slice(0, 180) + ' ' + (sentences[0] || ''))
    : shuffled;
  return [base, shuffled, stripped, contextAnchored];
}

async function runBlackBoxFallback(response, context) {
  const candidates = generateCandidates(response, context);
  const vectors    = candidates.map(c => tfVector(tokenise(c)));

  const similarities = [];
  for (let i = 0; i < vectors.length; i++) {
    for (let j = i + 1; j < vectors.length; j++) {
      similarities.push({
        pair: [i, j],
        similarity: parseFloat(tfCosineSimilarity(vectors[i], vectors[j]).toFixed(3)),
      });
    }
  }

  const avgSim = similarities.length > 0
    ? similarities.reduce((s, x) => s + x.similarity, 0) / similarities.length
    : 0;

  const confidence = parseFloat(Math.min(0.98, 0.3 + avgSim * 0.7).toFixed(3));

  return {
    scorer:       'BlackBoxScorer',
    method:       'tfidf_fallback',
    candidates:   candidates.length,
    similarities,
    avg_similarity: parseFloat(avgSim.toFixed(3)),
    confidence,
    interpretation: confidence >= 0.7
      ? 'Consistent across samples — low hallucination risk'
      : confidence >= 0.5
        ? 'Moderate consistency — some uncertainty detected'
        : 'Low consistency — high hallucination risk',
  };
}

// ── Main scorer ───────────────────────────────────────────────────────────────
async function runBlackBoxScorer({ response, context = '', secondSample = '', embedText = null, cosineSimilarity = null }) {
  const canUseRealPath = typeof embedText === 'function' && typeof cosineSimilarity === 'function'
    && secondSample && secondSample.trim().length > 0 && response && response.trim().length > 0;

  if (!canUseRealPath) {
    return runBlackBoxFallback(response, context);
  }

  const [vecA, vecB] = await Promise.all([embedText(response), embedText(secondSample)]);

  if (!vecA || !vecB) {
    return runBlackBoxFallback(response, context);
  }

  const semanticSimilarity = cosineSimilarity(vecA, vecB);
  const confidence = parseFloat(Math.max(0, Math.min(0.98, semanticSimilarity)).toFixed(3));

  return {
    scorer:       'BlackBoxScorer',
    method:       'self_consistency_embedding',
    candidates:   2,
    avg_similarity: parseFloat(semanticSimilarity.toFixed(3)),
    confidence,
    resample_preview: secondSample.slice(0, 160) + (secondSample.length > 160 ? '…' : ''),
    interpretation: confidence >= 0.7
      ? 'Independent resample is semantically consistent — low hallucination risk'
      : confidence >= 0.5
        ? 'Moderate consistency across resamples — some uncertainty detected'
        : 'Independent resample diverges significantly — high hallucination risk',
  };
}

module.exports = { runBlackBoxScorer };
